apiVersion: v1
kind: Template
labels:
  template: s2i-ocp-ansible-operations
message: A new OCP Ansible playbook has been created in your project.
metadata:
  annotations:
    openshift.io/display-name: OCP Ansible Playbook
    tags: ansible,openshift
    version: 1.0.0
  name: s2i-ocp-ansible-operations
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      application: ${PLAYBOOK_NAME}
    name: ${PLAYBOOK_NAME}
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: s2i-ocp-ansible-operations
  spec:
   dockerImageRepository: docker.io/miticojo/s2i-ocp-ansible-operations
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      application: ${PLAYBOOK_NAME}
    name: ${PLAYBOOK_NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${PLAYBOOK_NAME}:latest
    source:
      contextDir: ${CONTEXT_DIR}
      git:
        ref: ${SOURCE_REPOSITORY_REF}
        uri: ${SOURCE_REPOSITORY_URL}
      type: Git
    strategy:
      sourceStrategy:
        forcePull: true
        from:
          kind: ImageStreamTag
          name: s2i-ocp-ansible-operations:latest
      type: Source
    triggers:
    - github:
        secret: ${GITHUB_WEBHOOK_SECRET}
      type: GitHub
    - generic:
        secret: ${GENERIC_WEBHOOK_SECRET}
      type: Generic
    - imageChange: {}
      type: ImageChange
    - type: ConfigChange
- apiVersion: v1
  kind: Pod
  metadata:
    name: ${PLAYBOOK_NAME}
  spec:
    containers:
    - env: []
      image: ${REGISTRY_SVC}/${NAMESPACE}/${PLAYBOOK_NAME}
      imagePullPolicy: Always
      name: ${PLAYBOOK_NAME}
    restartPolicy: Never
parameters:
- description: The name for the application.
  displayName: Playbook Name
  name: PLAYBOOK_NAME
  required: true
  value: ocp-ansible-operations-playbook
- description: Git source URI for application
  displayName: Git Repository URL
  name: SOURCE_REPOSITORY_URL
  required: true
  value: https://github.com/miticojo/s2i-ocp-ansible-operations
- description: Git branch/tag reference
  displayName: Git Reference
  name: SOURCE_REPOSITORY_REF
  value: master
- description: Path within Git project to build; empty for root project directory.
  displayName: Context Directory
  name: CONTEXT_DIR
  value: example
- description: GitHub trigger secret
  displayName: Github Webhook Secret
  from: '[a-zA-Z0-9]{8}'
  generate: expression
  name: GITHUB_WEBHOOK_SECRET
  required: true
- description: Generic build trigger secret
  displayName: Generic Webhook Secret
  from: '[a-zA-Z0-9]{8}'
  generate: expression
  name: GENERIC_WEBHOOK_SECRET
  required: true
- description: Current Project Name.
  displayName: Current Project
  name: NAMESPACE
  required: true
- description: Registry Service Hostname:Port.
  displayName: Registry Hostname:Port
  name: REGISTRY_SVC
  value: 172.30.1.1:5000
  required: true
